CREATE DATABASE HR_PROJECT;
USE HR_PROJECT;
SELECT * FROM HR;

---OVERALL ATTRITION
SELECT COUNT (CASE WHEN ATTRITION = 'YES' THEN 1 END) AS ATTRITIONCOUNT,
       COUNT (*) AS TOTAL_EMP
FROM HR;

---NO. OF PEOPLE DOING OVERTIME AND IS THERE ANY CO RELATION
SELECT OVERTIME FROM HR;

SELECT 
       COUNT(CASE WHEN OVERTIME = 'NO' THEN 1 END) AS NOVERTIME_COUNT,
	   COUNT(CASE WHEN OVERTIME = 'YES' THEN 1 END) AS OVERTIME_COUNT,
	   COUNT(*) AS TOTAL_EMP

FROM HR
WHERE ATTRITION = 'YES';

---CONCLUSION 
-----110 PEOPLE DOESNT DOES NOT DO OVERTIME STILL THEY LEFT COMPANY
----AND 127 WAS DOING OVERTIME AND LEFT THE COMPANY
----THUS THERE IS NOO CORELATION OF OVERTIME WITH ATTRITION

---GENDER DISTRIBUTION IN THE COMPANY

SELECT GENDER,COUNT(*) FROM HR
GROUP BY GENDER;

SELECT GENDER,COUNT(*) FROM HR
WHERE ATTRITION = 'YES'
GROUP BY GENDER;

---CONCLUSION
---OUT OF 882 ,150 MALE LEFT THE COMPANY AND OUT OF 588 , 87 FEMALE LEFT THE COMPANY
---THUS THERE IS NO ROLE OF GENDER IN LEAVING THE COMPANY


---THE EFFECT OF PERFORMANCE RATING IN ATTRITION

SELECT PERFORMANCERATING , COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS ATTRITION_COUNT

FROM HR
GROUP BY PERFORMANCERATING;

---CONCLUSION 
---WHEN THE PERFORMANCERATING IS HIGH ,LESS ATTRITION HAPPENS
---WHEN THE PERFORMANCE RATING IS LOW, MORE ATTRTION HAPPENS
---THUS, THERE IS NEGATIVE CORRELATION AMONGST PREFORMANCE RATING AND ATTRITION

---ATTRITION COUNT BASED ON THE JOB ROLE

SELECT JOBROLE,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY JOBROLE
ORDER BY ATTRITION_COUNT DESC;

---CONCLUSION
----AROUND 60% OF ATTRITION ARE HAPPENING FROM THE LABORATORY TECHNICIAN,SALES EXECUTIVE AND RESEARCH SCIENTIST

---ATTRITION COUNT BASED ON DISTANCE FROM HOME

SELECT DISTANCEFROMHOME,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY DISTANCEFROMHOME
ORDER BY ATTRITION_COUNT DESC;

---CONCLUSION
---DATA IS SCATTERED HERE , THERE IS NO CORRELATION IN ATTRITION AND DISTANCE FROM HOME

---ATTRITION COUNT BASED ON DEPARTMENT

SELECT DEPARTMENT,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY DEPARTMENT
ORDER BY ATTRITION_COUNT DESC;

---CONCLUSION
--MOST OF THE ATTRITION HAPPENED FROM THE R&D DEPARTMENT

---ATTRITION COUNT BASED ON PERCENTAGESALARYHIKE

SELECT PERCENTSALARYHIKE,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY PERCENTSALARYHIKE
ORDER BY ATTRITION_COUNT DESC;

---CONCLUSION
---HEIGHER THE PERCENTAGE HIKE IN SALARY LOWER THE ATTRITION AND VICE VERSA
---THUS,THERE IS THE NEGATIVE COR-RELATION IN PERCENTHIKE AND ATTRITION


---ATTRITION COUNT BASED ON EDUCATION FIELD

SELECT EDUCATIONFIELD,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY EDUCATIONFIELD
ORDER BY ATTRITION_COUNT DESC;

---CONCLUSION 
---LIFE SCIENCE ,MEDICAL ETC HAS MANY OPPTUNITY SO THE IS HIGH IN MARKET SO THE ATTRITION IS HIGH

---ATTRITION COUNT BASED ON YEARNS IN CURRENT ROLE

SELECT YearsInCurrentRole,COUNT(CASE WHEN Attrition = 'YES' THEN 1 END ) AS ATTRITION_COUNT FROM HR
WHERE YEARSINCURRENTROLE > (SELECT AVG(CAST(YEARSINCURRENTROLE AS INT)) FROM HR)
GROUP BY YEARSINCURRENTROLE
ORDER BY ATTRITION_COUNT DESC;
---as years in current role col has varchar datatype so to find av we have to typecast it in int

---conclusion
---we dont have very clear picture but yes most of the attrition happens in the year between 5-10

---to know the datatype of col
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HR'
  AND COLUMN_NAME = 'YearsInCurrentRole';


---ATTRITION COUNT BASED ON JOB SATISFACTION AND MONTHLY INCOME
SELECT JOBSATISFACTION,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES' AND MonthlyIncome < (SELECT AVG(CAST(MONTHLYINCOME AS INT)) FROM HR)
GROUP BY JOBSATISFACTION;

---HERE I COMPAIR TWO COLUMN MONTLY INCOME AND JOBSATISFACTION
-- AND I CONCLUDE THAT MONTLY INCOME PLAYS A VITAL ROLE IN ATTRITION COUNT IRRESPECTIVE THE SATISFACTION FROM THE JOB IS ON THE HIGHER SIDE


---EMPLOYEE ATTRITION BASED ON THE AGE RANGE
SELECT CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-49'
			ELSE '60 OR OLDER'
			END AS 'AGE RANGE',
			COUNT(*) AS 'NUMBER OF ATTRITION BASED ON AGE RANGE'
FROM HR
WHERE ATTRITION = 'YES' AND YEARSATCOMPANY >= 1
GROUP BY CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-49'
			ELSE '60 OR OLDER'
			END;


--CONCLUSION
--HERE I MADE BUCKET OF AGE AND SCINCE WE DONT HAVE AGE RANGE COL IN TABLE SO UNDER GROUP BY COMMOND WE WILL PUSH WHOLE CONDITION OF AGE RANGE
-- THE YOUNG PEOPLE MAKES MORE ATTRITION THAN THE OLDER ONE

---ATTRITION BASED ON ENVIRONMENTSATISFACTION AND RELATIONSHIPSATISFACTION

SELECT ENVIRONMENTSATISFACTION,RELATIONSHIPSATISFACTION,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY ENVIRONMENTSATISFACTION,RELATIONSHIPSATISFACTION
ORDER BY 'ATTRITION_COUNT' DESC;


---CONCLUSION
-- THERE IS NO RELATION IN ENVIRONMENTSATISFACTION,RELATIONSHIPSATISFACTION AND ATTRTION


SELECT ENVIRONMENTSATISFACTION,RELATIONSHIPSATISFACTION,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES' AND MONTHLYINCOME < (SELECT AVG(CAST(MONTHLYINCOME AS INT)) FROM HR)
GROUP BY ENVIRONMENTSATISFACTION,RELATIONSHIPSATISFACTION
ORDER BY 'ATTRITION_COUNT' DESC;

---CONCLUSION
--FROM THE ABOVE WE SEE THAT THERE IS NO RELATION BUT WHERE WE COMPAIR IT WITH MONTHLY INCOME THEN WE GET TO KNOW THAT MONTHLY INCOME IS PAYING A 
---VITAL ROLE IN THE ATTRTION 


---ATTRITION BASED ON SALARIES
SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 'YES' AND DailyRate < (SELECT AVG(CAST(DAILYRATE AS INT)) FROM HR);


SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 'YES' AND MonthlyRate < (SELECT AVG(CAST(MONTHLYRATE AS INT)) FROM HR) 

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 'YES' AND MonthlyIncome < (SELECT AVG(CAST(MONTHLYINCOME AS INT)) FROM HR);

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 'YES' AND DailyRate < (SELECT AVG(CAST(DAILYRATE AS INT)) FROM HR) 
AND MonthlyRate < (SELECT AVG(CAST(MONTHLYRATE AS INT)) FROM HR) 
AND MonthlyIncome < (SELECT AVG(CAST(MONTHLYINCOME AS INT)) FROM HR);

--CONCLUSION
---MONTHLY INCOME PLAYS A VITAL ROLE IN ATTRITION


---ATTRITION BASED ON MARITAL STATUS
SELECT MARITALSTATUS,COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 'YES'
GROUP BY MaritalStatus;
--CONCLUSION
---SINGLE PEOPLE MADE MORE ATTRITION AS THEY ARE MORE INTO EXPLORING AND READY FOR THE RISK

--FINAL CONCLUSION
---MONTHLY INCOME, THE PERFORMANE RATING,SALARY HIKE,OVERTIME,WORK LIFE BALANCE, YEARS AT COMPANY, MARITAL STATUS 
--ARE PLAYING MORE VITAL ROLE IN THE ATTRTION IN THE COMPANY